<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR7cn3gd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR7cn3gd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR7cn3gd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerR7cn3gd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerR7cn3gd\appProdProjectContainer(array(
    'container.build_hash' => 'R7cn3gd',
    'container.build_id' => 'c4ebd1ee',
    'container.build_time' => 1547771792,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerR7cn3gd');
