<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQmsedrh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQmsedrh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerQmsedrh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerQmsedrh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerQmsedrh\appProdProjectContainer([
    'container.build_hash' => 'Qmsedrh',
    'container.build_id' => '6d9d5ee5',
    'container.build_time' => 1554778037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQmsedrh');
