<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOwxadrx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOwxadrx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOwxadrx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOwxadrx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOwxadrx\appProdProjectContainer([
    'container.build_hash' => 'Owxadrx',
    'container.build_id' => '59e0ef23',
    'container.build_time' => 1555989695,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOwxadrx');
